// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQCr4WKwxrDHYO8RM7OFuHUQuIBcNJXKM',
    appId: '1:740935125293:web:e168ca17d67e4277c4eba4',
    messagingSenderId: '740935125293',
    projectId: 'corebalt-bakecity-app',
    authDomain: 'corebalt-bakecity-app.firebaseapp.com',
    storageBucket: 'corebalt-bakecity-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcAEYwuBKu8VzU5KdCe-V84CqVd4w9Cnw',
    appId: '1:740935125293:android:42cca5a03a11465dc4eba4',
    messagingSenderId: '740935125293',
    projectId: 'corebalt-bakecity-app',
    storageBucket: 'corebalt-bakecity-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrXwIxcFdIJEya3tPCXT9t6Z4fExrgIGg',
    appId: '1:740935125293:ios:eafc66dd881f87ffc4eba4',
    messagingSenderId: '740935125293',
    projectId: 'corebalt-bakecity-app',
    storageBucket: 'corebalt-bakecity-app.firebasestorage.app',
    iosBundleId: 'com.example.bakecity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrXwIxcFdIJEya3tPCXT9t6Z4fExrgIGg',
    appId: '1:740935125293:ios:eafc66dd881f87ffc4eba4',
    messagingSenderId: '740935125293',
    projectId: 'corebalt-bakecity-app',
    storageBucket: 'corebalt-bakecity-app.firebasestorage.app',
    iosBundleId: 'com.example.bakecity',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQCr4WKwxrDHYO8RM7OFuHUQuIBcNJXKM',
    appId: '1:740935125293:web:0bed05545f130b03c4eba4',
    messagingSenderId: '740935125293',
    projectId: 'corebalt-bakecity-app',
    authDomain: 'corebalt-bakecity-app.firebaseapp.com',
    storageBucket: 'corebalt-bakecity-app.firebasestorage.app',
  );
}
